name: Deploy One-L Tool to AWS Dev Env

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
      STACK_NAME: OneL-DEV

    steps:
    # Step 1: Check out the repository's code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python for CDK
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Set up Node.js with the version required by your project
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Step 4: Install Python dependencies (from the root folder)
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Install frontend dependencies (in 'one_l/user_interface')
    - name: Install frontend dependencies
      run: |
        cd one_l/user_interface
        npm install

    # Step 6: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 7: Bootstrap the AWS environment (from the root folder)
    - name: Bootstrap AWS environment
      run: cdk bootstrap

    # Step 8: Deploy the CDK stack (from the root folder)
    - name: Deploy CDK stack
      run: cdk deploy ${{ env.STACK_NAME }} --require-approval never
      env:
        ENVIRONMENT: dev

    # Step 9: Fetch CloudFormation outputs and save to a file
    - name: Fetch CloudFormation Outputs
      run: |
        aws cloudformation describe-stacks --stack-name ${{ env.STACK_NAME }} --query "Stacks[0].Outputs" > stack-outputs.json
        cat stack-outputs.json  # Just to verify in logs if needed

    # Step 10: Upload the output file as an artifact (optional)
    - name: Upload Outputs as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: stack-outputs
        path: stack-outputs.json
